export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface-bright": "#31394d",
          "inverse-on-surface": "#283044",
          "primary-fixed": "#c4e7ff",
          "on-primary": "#00354a",
          "tertiary-container": "#30c88f",
          "on-tertiary": "#003824",
          "inverse-primary": "#00668a",
          "tertiary-fixed": "#6ffbbe",
          "on-secondary-fixed-variant": "#2f3aa3",
          "on-secondary": "#131e8c",
          "secondary-fixed": "#e0e0ff",
          "error": "#ffb4ab",
          "surface-container-highest": "#2d3449",
          "surface": "#0b1326",
          "error-container": "#93000a",
          "surface-container-high": "#222a3d",
          "on-tertiary-fixed": "#002113",
          "on-background": "#dae2fd",
          "on-secondary-fixed": "#000767",
          "tertiary-fixed-dim": "#4edea3",
          "surface-container": "#171f33",
          "outline": "#87929a",
          "background": "#0b1326",
          "primary-container": "#38bdf8",
          "inverse-surface": "#dae2fd",
          "on-surface": "#dae2fd",
          "on-error-container": "#ffdad6",
          "tertiary": "#56e5a9",
          "secondary-fixed-dim": "#bdc2ff",
          "on-tertiary-fixed-variant": "#005236",
          "surface-container-lowest": "#060e20",
          "surface-container-low": "#131b2e",
          "on-surface-variant": "#bdc8d1",
          "secondary": "#bdc2ff",
          "on-primary-container": "#004965",
          "surface-tint": "#7bd0ff",
          "surface-dim": "#0b1326",
          "primary": "#8ed5ff",
          "on-primary-fixed": "#001e2c",
          "on-error": "#690005",
          "on-secondary-container": "#a8afff",
          "primary-fixed-dim": "#7bd0ff",
          "outline-variant": "#3e484f",
          "on-primary-fixed-variant": "#004c69",
          "on-tertiary-container": "#004e34",
          "surface-variant": "#2d3449",
          "secondary-container": "#2f3aa3"
      },
      "fontFamily": {
          "display-lg": ["Plus Jakarta Sans", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "headline-md": ["Plus Jakarta Sans", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "label-md": ["Inter", "sans-serif"],
          "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
          "label-sm": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
          "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
          "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
